spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/habit_tracker
    username: postgres
    password: Robotghost20
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml